import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import netCDF4 as nc
import xarray as xr
from pathlib import Path
from datetime import datetime, timedelta
import warnings
import os
import json
from scipy.spatial import cKDTree
from scipy.optimize import differential_evolution
import sys
from tqdm import tqdm

warnings.filterwarnings('ignore')

# Add parent directory to path to import custom modules
sys.path.append(str(Path.cwd().parent))

print("Libraries imported successfully!")


# File paths
SMAP_FILE = Path(r'G:\SM2RAIN-irrigation_Final\data\SMAP_data\SPL3SMP_E_Ludhiana_ROI.nc')
# ^ NASA SMAP Level-3 soil moisture product (SPL3SMP_E), clipped to the
#   validation region of interest (ROI). Contains AM/PM soil moisture
#   observations on the EASE-Grid at each overpass time.

CLASSIFICATION_FILE = Path(r'G:\SM2RAIN-irrigation_Final\calibration\SM_classes\SM_classes_ludhiana.csv')
# ^ CSV mapping each SMAP grid point (lat/lon) to one of the NUM_CLASSES
#   rainfall intensity classes. Generated by the pre-processing step that
#   bins historical rainfall totals at each location.

DATES_DIR = Path(r'G:\SM2RAIN-irrigation_Final\calibration\calib_dates_rainfall_filtered')
# ^ Directory containing one CSV per class (class_1_filtered_dates.csv …
#   class_5_filtered_dates.csv). Each CSV lists the SMAP observation dates
#   that fall within ±N days of a rainfall event for that class — these are
#   the windows used for calibration.

TEMP_FILE = Path(r'G:\SM2RAIN-irrigation_Final\data\temp_data\AgERA5_daily_mean_ludhiana.nc')
# ^ Gridded daily mean 2-m air temperature (°C) from the Copernicus
#   agERA5 dataset, merged into a single NetCDF covering the full
#   validation period. Used to compute PET via the Hargreaves method.

PRECIP_FILE = Path(r'G:\SM2RAIN-irrigation_Final\data\precipitation_data\GPM_IMERG_ludhiana_final_run.nc')
# ^ Daily precipitation (mm/day) from GPM IMERG Final Run, pre-processed
#   and merged for the validation region. Serves as the reference rainfall
#   that SM2RAIN parameters are calibrated against.

# Output directory
OUTPUT_DIR = Path(r'G:\SM2RAIN-irrigation_Final\calibration\per_class_parameters_ludhiana_correct_temp')
# ^ Where calibration results are written:
#     class_<i>_calibration_results.json  – per-class optimised parameters
#     all_classes_calibration_results.json – combined results
#     all_classes_best_parameters.csv      – summary table
#     parameter_variation_by_class.png     – parameter bar charts
#     rmse_kge_comparison_by_class.png     – performance comparison plots

# Output directory
# OUTPUT_DIR = Path(r'G:\sm2rain-irrigation\calibration\per_class_results_ludhiana')
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

# SM2RAIN configuration
T_EXPONENTIAL_FILTER = 5.0  # days
FILL_VALUE = -9999.0
SM_SOURCE = 'BOTH'  # 'AM', 'PM', or 'BOTH'

# Calibration mode
USE_AGGREGATED_WINDOWS = True  # True: aggregate over 5-day windows, False: use daily data

# Objective function: 'KGE' (Kling-Gupta Efficiency) or 'RMSE' (Root Mean Square Error)
# KGE: maximized (range -inf to 1.0, perfect = 1.0)  --> optimizer minimizes (1 - KGE)
# RMSE: minimized (range 0 to inf, perfect = 0.0)    --> optimizer minimizes RMSE directly
OBJECTIVE_FUNCTION = 'KGE'  # Switch here to change the objective function globally

# Calibration strategy
# False → per-point: each station is calibrated independently with its own events,
#          then the station with the best score is selected for the class.
#          Optimizer sees: N_events  data points per run  (e.g.  25 events)
#
# True  → pooled: ALL events from ALL stations in the class are merged into one
#          dataset and a single optimization is run for the whole class.
#          Optimizer sees: N_stations × N_events  data points  (e.g. 25×25 = 625)
POOLED_CALIBRATION = False  # Switch here

# Number of classes
NUM_CLASSES = 5

print("Configuration loaded:")
print(f"  SMAP file: {SMAP_FILE}")
print(f"  Classification file: {CLASSIFICATION_FILE}")
print(f"  Dates directory: {DATES_DIR}")
print(f"  Output directory: {OUTPUT_DIR}")
print(f"  T filter: {T_EXPONENTIAL_FILTER} days")
print(f"  Number of classes: {NUM_CLASSES}")
print(f"  Calibration mode: {'AGGREGATED 5-day windows' if USE_AGGREGATED_WINDOWS else 'DAILY data'}")
print(f"  Objective function: {OBJECTIVE_FUNCTION}")
print(f"  Calibration strategy: {'POOLED (all stations × all events)' if POOLED_CALIBRATION else 'PER-POINT (best station selected)'}")


def load_smap_data(smap_file, sm_source='BOTH', fill_value=-9999.0):
    """
    Load SMAP soil moisture data from NetCDF file.
    Based on SPL3SMP_reader.ipynb
    """
    print(f"Loading SMAP data from: {smap_file}")
    
    # Open NetCDF file
    ds = nc.Dataset(smap_file, 'r')
    
    # Read variables
    time_j2000 = ds.variables['time'][:]
    epoch = datetime(2000, 1, 1)
    time_dt = np.array([epoch + timedelta(seconds=float(t)) for t in time_j2000])
    
    latitude = ds.variables['latitude'][:]
    longitude = ds.variables['longitude'][:]
    soil_moisture_am = ds.variables['soil_moisture_am'][:]
    soil_moisture_pm = ds.variables['soil_moisture_pm'][:]
    
    ds.close()
    
    # Create DataFrame
    df = pd.DataFrame({
        'time': time_dt,
        'latitude': latitude,
        'longitude': longitude,
        'soil_moisture_am': soil_moisture_am,
        'soil_moisture_pm': soil_moisture_pm
    })
    
    # Filter out fill values
    df = df[(df['latitude'] != fill_value) & (df['longitude'] != fill_value)]
    df = df[(df['soil_moisture_am'] != fill_value) | (df['soil_moisture_pm'] != fill_value)]
    
    # Create combined soil moisture column
    if sm_source == 'AM':
        df['soil_moisture'] = df['soil_moisture_am'].replace(fill_value, np.nan)
    elif sm_source == 'PM':
        df['soil_moisture'] = df['soil_moisture_pm'].replace(fill_value, np.nan)
    elif sm_source == 'BOTH':
        sm_am = df['soil_moisture_am'].replace(fill_value, np.nan)
        sm_pm = df['soil_moisture_pm'].replace(fill_value, np.nan)
        df['soil_moisture'] = np.nanmean([sm_am, sm_pm], axis=0)
    
    # Remove NaN values
    df = df.dropna(subset=['soil_moisture'])
    
    # Convert time to datetime
    df['date'] = pd.to_datetime(df['time']).dt.date
    
    print(f"  Loaded {len(df):,} valid observations")
    print(f"  Date range: {df['time'].min()} to {df['time'].max()}")
    print(f"  Unique locations: {df.groupby(['latitude', 'longitude']).ngroups}")
    print(f"  Lat range: {df['latitude'].min():.4f} to {df['latitude'].max():.4f}")
    print(f"  Lon range: {df['longitude'].min():.4f} to {df['longitude'].max():.4f}")
    
    return df

# Load SMAP data
smap_df = load_smap_data(SMAP_FILE, SM_SOURCE, FILL_VALUE)
print("\nFirst few rows:")
print(smap_df.head())

# Load classification CSV
classification_df = pd.read_csv(CLASSIFICATION_FILE)
print(f"Classification data loaded: {len(classification_df)} records")
print(f"Rainfall classes: {sorted(classification_df['rainfall_class'].unique())}")
print(f"\nClass distribution:")
print(classification_df['rainfall_class'].value_counts().sort_index())
print(f"\nFirst few rows:")
print(classification_df.head(10))

# Load filtered dates for each class
# Supports two filename conventions used by different upstream notebooks:
#   calib_dates_ludhiana/           →  class_{i}_calib_dates.csv
#   calib_dates_rainfall_filtered/  →  class_{i}_filtered_dates.csv
class_dates = {}
class_event_info = {}  # Store full event information for aggregation

# Candidate filename patterns tried in order
FILENAME_PATTERNS = [
    'class_{i}_filtered_dates.csv',   # 4-1_SMAP_rainfall_filter output
    'class_{i}_calib_dates.csv',      # 3_SMAP_calib_dates_per_class output
]

for class_id in range(1, NUM_CLASSES + 1):
    # Find the first matching file for this class
    date_file = None
    for pattern in FILENAME_PATTERNS:
        candidate = DATES_DIR / pattern.format(i=class_id)
        if candidate.exists():
            date_file = candidate
            break

    if date_file is None:
        print(f"WARNING: No date file found for class {class_id} in {DATES_DIR}")
        print(f"  Tried: {[DATES_DIR / p.format(i=class_id) for p in FILENAME_PATTERNS]}")
        continue

    dates_df = pd.read_csv(date_file)
    dates_df['date'] = pd.to_datetime(dates_df['date']).dt.date
    dates_df['event_date'] = pd.to_datetime(dates_df['event_date']).dt.date
    class_dates[class_id] = dates_df['date'].unique()
    class_event_info[class_id] = dates_df  # Store full dataframe
    print(f"Class {class_id}: {len(class_dates[class_id])} dates loaded "
          f"({dates_df['event_date'].nunique()} events)  [{date_file.name}]")

print(f"\nTotal classes with dates: {len(class_dates)}")
print(f"Source directory: {DATES_DIR}")


def load_netcdf_gridded_data(file_path, var_name=None):
    """
    Load gridded NetCDF data (temperature or precipitation).

    Strategy:
    1. Open with decode_times=True (works for standard CF-convention time).
    2. If all resulting dates are clearly wrong (year < 1980 after conversion),
       reopen with decode_times=False and use an explicit 'date' data variable
       when available (byte-string format DD-MM-YYYY, as used by GPM IMERG).
    """
    print(f"Loading data from: {file_path}")

    def _build_df(ds, var_name_inner):
        """Core helper: dataset → flat DataFrame."""
        data = ds[var_name_inner]
        lat_names  = ['lat', 'latitude', 'y']
        lon_names  = ['lon', 'longitude', 'x']
        time_names = ['time', 'date']
        lat_dim  = next((d for d in data.dims if d in lat_names),  None)
        lon_dim  = next((d for d in data.dims if d in lon_names),  None)
        time_dim = next((d for d in data.dims if d in time_names), None)
        if not all([lat_dim, lon_dim, time_dim]):
            raise ValueError("Could not identify lat/lon/time dimensions")
        df = data.to_dataframe().reset_index()
        df = df.rename(columns={
            lat_dim:        'lat',
            lon_dim:        'lon',
            time_dim:       'time',
            var_name_inner: 'value'
        })
        return df

    # ── Pass 1: standard CF decoding ────────────────────────────────────────
    ds = xr.open_dataset(file_path, decode_times=True)

    # Auto-detect variable name
    if var_name is None:
        candidates = [
            'Temperature_Air_2m_Mean_24h', 'temperature', 'temp', 't2m', 'tas',
            'precipitation', 'precip', 'tp', 'pr', 'precipitationCal',
        ]
        var_name = next((v for v in candidates if v in ds.variables), None)
    if var_name is None:
        raise ValueError(f"Could not auto-detect variable name in {file_path}")
    print(f"  Using variable: {var_name}")

    df = _build_df(ds, var_name)

    # Convert time column to datetime
    if not pd.api.types.is_datetime64_any_dtype(df['time']):
        df['time'] = pd.to_datetime(df['time'], errors='coerce')

    df = df.dropna(subset=['time'])

    # Check whether the decoded dates look sensible (year >= 1980)
    valid_years = (df['time'].dt.year >= 1980).sum() if len(df) else 0
    dates_ok = valid_years > 0

    # ── Pass 2: fallback for files with no CF time units ────────────────────
    if not dates_ok:
        print(f"  CF time decode failed (all dates < 1980); trying 'date' variable fallback...")
        ds.close()
        ds = xr.open_dataset(file_path, decode_times=False)
        df = _build_df(ds, var_name)

        if 'date' in ds.data_vars:
            raw_dates = ds['date'].values
            parsed_dates = []
            for d in raw_dates:
                if isinstance(d, (bytes, np.bytes_)):
                    d = d.decode('utf-8')
                try:
                    parsed_dates.append(pd.to_datetime(d, dayfirst=True))
                except Exception:
                    parsed_dates.append(pd.NaT)
            time_map = {i: parsed_dates[i] for i in range(len(parsed_dates))}
            df['time'] = df['time'].map(time_map)
            print(f"  Time decoded via 'date' variable (DD-MM-YYYY).")
        else:
            df['time'] = pd.to_datetime(df['time'], errors='coerce')
            print(f"  WARNING: no 'date' fallback found; dates may be incorrect.")

        df = df.dropna(subset=['time'])

    df['date'] = df['time'].dt.date

    print(f"  Shape: {len(df)} records")
    print(f"  Unique locations: {df.groupby(['lat', 'lon']).ngroups}")
    print(f"  Date range: {df['time'].min()} to {df['time'].max()}")

    return df, ds

# Load temperature data
temp_df, temp_ds = load_netcdf_gridded_data(TEMP_FILE)
temp_df['value'] = temp_df['value'] - 273.15  # Convert Kelvin → Celsius
print(f"  Temperature converted from Kelvin to Celsius (sample range: {temp_df['value'].min():.1f} to {temp_df['value'].max():.1f} °C)")
print("\nTemperature data loaded")

# Load precipitation data
precip_df, precip_ds = load_netcdf_gridded_data(PRECIP_FILE)
print("\nPrecipitation data loaded")


def resample_to_smap_grid(source_df, smap_coords, value_col='value'):
    """
    Resample source data (temperature or precipitation) to SMAP grid using nearest neighbor.
    
    Parameters:
    -----------
    source_df : DataFrame
        Source data with columns: lat, lon, date, value
    smap_coords : DataFrame
        SMAP coordinates with columns: latitude, longitude
    value_col : str
        Name of the value column in source_df
    
    Returns:
    --------
    DataFrame with resampled data matched to SMAP grid
    """
    print("\nResampling to SMAP grid using nearest neighbor...")
    
    # Get unique source coordinates
    source_coords = source_df[['lat', 'lon']].drop_duplicates().values
    smap_coords_array = smap_coords[['latitude', 'longitude']].values
    
    print(f"  Source grid points: {len(source_coords)}")
    print(f"  Target SMAP grid points: {len(smap_coords_array)}")
    
    # Build KD-tree for source coordinates
    tree = cKDTree(source_coords)
    
    # Find nearest neighbors for each SMAP point
    distances, indices = tree.query(smap_coords_array)
    
    print(f"  Mean distance to nearest neighbor: {distances.mean():.4f} degrees")
    print(f"  Max distance to nearest neighbor: {distances.max():.4f} degrees")
    
    # Create mapping dictionary
    mapping = {}
    for i, (smap_lat, smap_lon) in enumerate(smap_coords_array):
        nearest_idx = indices[i]
        source_lat, source_lon = source_coords[nearest_idx]
        mapping[(smap_lat, smap_lon)] = (source_lat, source_lon)
    
    # Apply mapping to create resampled dataframe
    resampled_data = []
    
    for (smap_lat, smap_lon), (source_lat, source_lon) in mapping.items():
        # Get all time series data for this source point
        subset = source_df[
            (source_df['lat'] == source_lat) & 
            (source_df['lon'] == source_lon)
        ].copy()
        
        if len(subset) > 0:
            subset['smap_lat'] = smap_lat
            subset['smap_lon'] = smap_lon
            resampled_data.append(subset)
    
    resampled_df = pd.concat(resampled_data, ignore_index=True)
    
    print(f"  Resampled data records: {len(resampled_df)}")
    
    return resampled_df

# Get unique SMAP coordinates
smap_coords = smap_df[['latitude', 'longitude']].drop_duplicates().reset_index(drop=True)
print(f"\nUnique SMAP grid points: {len(smap_coords)}")

# Resample temperature to SMAP grid
temp_resampled = resample_to_smap_grid(temp_df, smap_coords)

# Resample precipitation to SMAP grid
precip_resampled = resample_to_smap_grid(precip_df, smap_coords)

print("\nResampling complete!")



def normalize_soil_moisture(sm_series, sm_min=None, sm_max=None):
    """
    Normalize soil moisture to relative wetness [0, 1].

    If sm_min / sm_max are provided (computed from the full time series for
    that station), those are used so the scaling reflects the true residual
    moisture / saturation range.  Otherwise the min/max of the passed series
    is used as a fallback.
    """
    if sm_min is None:
        sm_min = sm_series.min()
    if sm_max is None:
        sm_max = sm_series.max()

    if sm_max - sm_min < 1e-6:
        return pd.Series(np.ones(len(sm_series)) * 0.5, index=sm_series.index)

    sm_rel = (sm_series - sm_min) / (sm_max - sm_min)
    # Clip to [0, 1] in case calibration-period values fall slightly outside
    # the global range due to measurement noise
    sm_rel = sm_rel.clip(0.0, 1.0)
    return sm_rel


def exponential_filter(sm_series, T):
    """
    Apply exponential smoothing filter.
    """
    alpha = 2.0 / (T + 1.0)
    sm_filtered = sm_series.ewm(alpha=alpha, adjust=False).mean()
    return sm_filtered


def compute_sm2rain_rainfall(sm_rel, Zstar, Ks, lam, T):
    """
    Compute SM2RAIN-estimated rainfall.
    
    Parameters:
    -----------
    sm_rel : pd.Series
        Relative soil moisture [0, 1]
    Zstar : float
        Effective soil depth (mm)
    Ks : float
        Saturated hydraulic conductivity (mm/day)
    lam : float
        Shape parameter
    T : float
        Time constant for exponential filter (days)
    
    Returns:
    --------
    pd.Series : Estimated rainfall (mm/day)
    """
    # Apply exponential filter
    sm_filtered = exponential_filter(sm_rel, T)
    
    # Compute time derivative of filtered soil moisture
    dsm_dt = sm_filtered.diff() / 1.0  # Daily data
    dsm_dt.iloc[0] = 0
    
    # Compute drainage term
    drainage = Ks * (sm_filtered ** lam)
    
    # SM2RAIN equation: P = Z* * dS/dt + Ks * S^lambda
    P_estimated = Zstar * dsm_dt + drainage
    
    # Clip negative values
    P_estimated = P_estimated.clip(lower=0)
    
    return P_estimated


def calculate_ra_mm_day(lat, day_of_year):
    """
    Calculate Extraterrestrial Radiation (Ra) in mm/day using FAO-56 methodology.

    Parameters
    ----------
    lat : float
        Latitude in decimal degrees.
    day_of_year : int or array-like
        Julian day (1–365/366).

    Returns
    -------
    float or np.ndarray : Ra in mm/day.
    """
    phi = np.radians(lat)
    d_r   = 1.0 + 0.033 * np.cos(2.0 * np.pi * day_of_year / 365.0)
    delta = 0.409 * np.sin((2.0 * np.pi * day_of_year / 365.0) - 1.39)
    tan_phi_delta = np.clip(-np.tan(phi) * np.tan(delta), -1.0, 1.0)
    omega_s = np.arccos(tan_phi_delta)
    G_sc = 0.0820  # Solar constant (MJ m⁻² min⁻¹)
    Ra_mj = (24.0 * 60.0 / np.pi) * G_sc * d_r * (
        omega_s * np.sin(phi) * np.sin(delta) +
        np.cos(phi) * np.cos(delta) * np.sin(omega_s)
    )
    return Ra_mj * 0.408  # Convert MJ/m²/day → mm/day


def compute_pet_hargreaves(temp_series, lat):
    """
    Compute potential evapotranspiration using the Hargreaves method with
    dynamic extraterrestrial radiation (Ra) computed via FAO-56 for each date.

    Parameters
    ----------
    temp_series : pd.Series
        Daily mean temperature (°C).  Index must be date-like so that
        day-of-year can be extracted.
    lat : float
        Latitude in decimal degrees.
    """
    doy = pd.to_datetime(temp_series.index).day_of_year
    Ra  = calculate_ra_mm_day(lat, doy.values)
    PET = 0.0023 * (temp_series + 17.8) * Ra
    return PET.clip(lower=0)


def sm2rain_with_et(sm_rel, temp_series, lat, Zstar, Ks, lam, Kc, T):
    """
    SM2RAIN with evapotranspiration correction.
    
    Total water input = P_estimated + Kc * PET
    """
    # Compute SM2RAIN rainfall
    P_sm2rain = compute_sm2rain_rainfall(sm_rel, Zstar, Ks, lam, T)
    
    # Compute PET
    PET = compute_pet_hargreaves(temp_series, lat)
    
    # Total water input
    total_water_input = P_sm2rain + Kc * PET
    
    return total_water_input, P_sm2rain, PET


def calculate_kge(simulated, observed):
    """
    Calculate the Kling-Gupta Efficiency (KGE).
    
    KGE = 1 - sqrt((r-1)^2 + (beta-1)^2 + (gamma-1)^2)
    where:
        r     = Pearson correlation coefficient
        beta  = mean_sim / mean_obs  (bias ratio)
        gamma = CV_sim / CV_obs      (variability ratio)
    
    Perfect score = 1.0
    Returns -9999.0 if insufficient valid data.
    """
    sim = np.asarray(simulated, dtype=float)
    obs = np.asarray(observed, dtype=float)
    
    # Mask out NaNs
    valid = ~np.isnan(sim) & ~np.isnan(obs)
    sim = sim[valid]
    obs = obs[valid]
    
    if len(sim) < 2:
        return -9999.0
    
    # Pearson correlation (r)
    r = np.corrcoef(sim, obs)[0, 1]
    if np.isnan(r):
        return -9999.0
    
    mean_obs = np.mean(obs)
    mean_sim = np.mean(sim)
    
    # Bias ratio (beta)
    beta = mean_sim / (mean_obs + 1e-6)
    
    # Variability ratio (gamma = CV_sim / CV_obs)
    cv_sim = np.std(sim) / (mean_sim + 1e-6)
    cv_obs = np.std(obs) / (mean_obs + 1e-6)
    gamma = cv_sim / (cv_obs + 1e-6)
    
    kge = 1.0 - np.sqrt((r - 1.0) ** 2 + (beta - 1.0) ** 2 + (gamma - 1.0) ** 2)
    return kge


def calculate_pearson_r(simulated, observed):
    """
    Compute the Pearson correlation coefficient between simulated and observed.
    Returns float('nan') if insufficient valid data.
    """
    sim = np.asarray(simulated, dtype=float)
    obs = np.asarray(observed, dtype=float)
    valid = ~np.isnan(sim) & ~np.isnan(obs)
    sim, obs = sim[valid], obs[valid]
    if len(sim) < 2:
        return float('nan')
    r = np.corrcoef(sim, obs)[0, 1]
    return float(r) if not np.isnan(r) else float('nan')


def compute_objective(simulated, observed, objective='KGE'):
    """
    Compute calibration objective to be MINIMIZED by the optimizer.
    
    Parameters:
    -----------
    simulated : array-like
        Model-estimated values
    observed : array-like
        Reference / observed values
    objective : str
        'KGE'  -> returns (1 - KGE);  perfect = 0, worse > 0
        'RMSE' -> returns RMSE;       perfect = 0, worse > 0
    
    Returns:
    --------
    float : scalar loss value (lower is better)
    """
    sim = np.asarray(simulated, dtype=float)
    obs = np.asarray(observed, dtype=float)
    
    if objective == 'KGE':
        kge = calculate_kge(sim, obs)
        if kge == -9999.0:
            return 1e6
        return 1.0 - kge  # Minimize (1 - KGE); perfect KGE=1 -> loss=0
    else:  # RMSE
        return np.sqrt(np.mean((sim - obs) ** 2))


print("SM2RAIN functions defined (KGE and RMSE objective supported).")



def calibrate_sm2rain_parameters(sm_series, temp_series, rain_reference, lat, T_filter,
                                  sm_global_min=None, sm_global_max=None):
    """
    Calibrate SM2RAIN parameters using differential evolution.
    
    Parameters:
    -----------
    sm_series : pd.Series
        Soil moisture time series (calibration period only)
    temp_series : pd.Series
        Temperature time series (aligned with sm_series)
    rain_reference : pd.Series
        Reference rainfall for calibration (aligned with sm_series)
    lat : float
        Latitude of the location
    T_filter : float
        Exponential filter time constant
    sm_global_min : float, optional
        S_min from the FULL time series for this station (residual / wilting point).
        If provided, normalization uses this instead of the calibration-period min.
    sm_global_max : float, optional
        S_max from the FULL time series for this station (saturation / max porosity).
        If provided, normalization uses this instead of the calibration-period max.
    
    Returns:
    --------
    dict : Calibrated parameters and objective score
    """
    # Normalize soil moisture using full-series min/max so that
    # S_relative = (S_raw - S_min_global) / (S_max_global - S_min_global)
    sm_rel = normalize_soil_moisture(sm_series, sm_global_min, sm_global_max)
    
    # Define objective function (minimized by optimizer)
    def objective(params):
        Zstar, Ks, lam, Kc = params
        
        try:
            # Compute SM2RAIN rainfall with ET
            total_water_input, _, _ = sm2rain_with_et(
                sm_rel, temp_series, lat, Zstar, Ks, lam, Kc, T_filter
            )
            
            # Use globally configured objective function
            return compute_objective(
                total_water_input.values, rain_reference.values, OBJECTIVE_FUNCTION
            )
        except Exception:
            return 1e6  # Return large penalty if computation fails
    
    # Parameter bounds
    bounds = [
        (0.001, 100.0),    # Zstar (mm)
        (0.001, 50.0),     # Ks (mm/day)
        (3.0, 15.0),       # lambda
        (0.001, 25.0)      # Kc
    ]
    
    # Run differential evolution
    result = differential_evolution(
        objective, bounds,
        seed=83, maxiter=1000, popsize=25,
        tol=0.005, atol=0.005, workers=1
    )
    
    Zstar_opt, Ks_opt, lam_opt, Kc_opt = result.x
    loss_opt = result.fun  # (1 - KGE) or RMSE depending on OBJECTIVE_FUNCTION
    
    # Compute both metrics for reporting
    total_water_input, _, _ = sm2rain_with_et(
        sm_rel, temp_series, lat, Zstar_opt, Ks_opt, lam_opt, Kc_opt, T_filter
    )
    rmse_final    = np.sqrt(np.mean((total_water_input.values - rain_reference.values) ** 2))
    kge_final     = calculate_kge(total_water_input.values, rain_reference.values)
    pearson_final = calculate_pearson_r(total_water_input.values, rain_reference.values)
    
    return {
        'Zstar': Zstar_opt,
        'Ks': Ks_opt,
        'lam': lam_opt,
        'Kc': Kc_opt,
        'rmse': rmse_final,
        'kge': kge_final,
        'pearson_r': pearson_final,
        'loss': loss_opt,          # The minimized objective value
        'objective_fn': OBJECTIVE_FUNCTION,
        'success': result.success
    }

print("Calibration function defined.")


def calibrate_sm2rain_aggregated(event_data_list, lat, T_filter,
                                  sm_global_min=None, sm_global_max=None):
    """
    Calibrate SM2RAIN parameters using aggregated 5-day windows.
    
    Parameters:
    -----------
    event_data_list : list of dicts
        Each dict contains aggregated data for one event:
        - sm_start: soil moisture at start of window
        - sm_end: soil moisture at end of window
        - rain_total: total rainfall over window
        - temp_mean: mean temperature over window
        - window_days: number of days in window
    lat : float
        Latitude of the location
    T_filter : float
        Exponential filter time constant
    sm_global_min : float, optional
        S_min from the FULL time series for this station (residual / wilting point).
        If provided, normalization uses this instead of the event-period min.
    sm_global_max : float, optional
        S_max from the FULL time series for this station (saturation / max porosity).
        If provided, normalization uses this instead of the event-period max.
    
    Returns:
    --------
    dict : Calibrated parameters and objective score
    """
    # Extract aggregated values
    rain_totals = np.array([evt['rain_total'] for evt in event_data_list])
    temp_means  = np.array([evt['temp_mean']  for evt in event_data_list])
    window_days = np.array([evt['window_days'] for evt in event_data_list])
    
    # -----------------------------------------------------------------------
    # Determine S_min / S_max for normalisation
    # Priority: global stats from the full time series (passed in as args).
    # Fallback: min/max over all SM values present in this event list.
    # -----------------------------------------------------------------------
    if sm_global_min is not None and sm_global_max is not None:
        sm_min = sm_global_min
        sm_max = sm_global_max
    else:
        all_sm_values = np.concatenate([[evt['sm_start'], evt['sm_end']] for evt in event_data_list])
        sm_min = all_sm_values.min()
        sm_max = all_sm_values.max()
    
    sm_range = sm_max - sm_min if (sm_max - sm_min) > 1e-6 else 1.0

    # Normalise: S_rel = (S_raw - S_min) / (S_max - S_min), clipped to [0, 1]
    sm_rel_start = np.clip(
        np.array([(evt['sm_start'] - sm_min) / sm_range for evt in event_data_list]), 0.0, 1.0
    )
    sm_rel_end = np.clip(
        np.array([(evt['sm_end'] - sm_min) / sm_range for evt in event_data_list]), 0.0, 1.0
    )
    
    # Define objective function (minimized by optimizer)
    def objective(params):
        Zstar, Ks, lam, Kc = params
        
        try:
            estimated_inputs = []
            
            for i in range(len(event_data_list)):
                # SM2RAIN water balance over window
                # P_total = Zstar * (SM_end - SM_start) + Ks * window_days * SM_mean^lambda + Kc * PET_mean * window_days

                sm_change_rel = sm_rel_end[i] - sm_rel_start[i]
                sm_mean_rel = (sm_rel_start[i] + sm_rel_end[i]) / 2.0

                # Dynamic Ra via FAO-56 using mid-window day-of-year
                doy = event_data_list[i].get('doy_mid', 180)
                Ra_dynamic = calculate_ra_mm_day(lat, doy)
                PET_daily = max(0.0, 0.0023 * (temp_means[i] + 17.8) * Ra_dynamic)

                # Total water input estimation
                # Note: storage term uses sm_range to convert dimensionless dS back to mm
                storage_term  = Zstar * sm_range * sm_change_rel
                drainage_term = Ks * window_days[i] * (sm_mean_rel ** lam)
                et_term       = Kc * PET_daily * window_days[i]

                total_input = storage_term + drainage_term + et_term
                estimated_inputs.append(max(0.0, total_input))
            
            estimated_inputs = np.array(estimated_inputs)
            
            # Use globally configured objective function
            return compute_objective(estimated_inputs, rain_totals, OBJECTIVE_FUNCTION)
        except Exception:
            return 1e6
    
    # Parameter bounds
    bounds = [
        (10.0, 250.0),    # Zstar (mm)
        (10, 250.0),      # Ks (mm/day)
        (3.0, 15.0),       # lambda
        (0, 1.5)         # Kc
    ]
    
    # Run differential evolution
    result = differential_evolution(
        objective,
        bounds,
        strategy='best1bin',    # Standard aggressive strategy
        mutation=(0.5, 1.5),    # High exploration
        recombination=0.9,      # High trait mixing
        seed=83,
        maxiter=2500,           # Increased to allow deep search
        popsize=30,            # MASSIVE initial search grid
        tol=1e-3,               # Relentless precision
        atol=1e-3,              # Relentless precision
        updating='deferred',    # Better for avoiding local minima
        workers=1
    )
    
    Zstar_opt, Ks_opt, lam_opt, Kc_opt = result.x
    loss_opt = result.fun  # (1 - KGE) or RMSE depending on OBJECTIVE_FUNCTION
    
    # Compute both metrics for reporting using optimal parameters
    estimated_inputs = []
    for i in range(len(event_data_list)):
        sm_change_rel = sm_rel_end[i] - sm_rel_start[i]
        sm_mean_rel   = (sm_rel_start[i] + sm_rel_end[i]) / 2.0
        doy           = event_data_list[i].get('doy_mid', 180)
        Ra_dynamic    = calculate_ra_mm_day(lat, doy)
        PET_daily     = max(0.0, 0.0023 * (temp_means[i] + 17.8) * Ra_dynamic)
        storage_term  = Zstar_opt * sm_range * sm_change_rel
        drainage_term = Ks_opt * window_days[i] * (sm_mean_rel ** lam_opt)
        et_term       = Kc_opt * PET_daily * window_days[i]
        estimated_inputs.append(max(0.0, storage_term + drainage_term + et_term))
    estimated_inputs = np.array(estimated_inputs)
    
    rmse_final    = np.sqrt(np.mean((estimated_inputs - rain_totals) ** 2))
    kge_final     = calculate_kge(estimated_inputs, rain_totals)
    pearson_final = calculate_pearson_r(estimated_inputs, rain_totals)
    
    return {
        'Zstar': Zstar_opt,
        'Ks': Ks_opt,
        'lam': lam_opt,
        'Kc': Kc_opt,
        'rmse': rmse_final,
        'kge': kge_final,
        'pearson_r': pearson_final,
        'loss': loss_opt,          # The minimized objective value
        'objective_fn': OBJECTIVE_FUNCTION,
        'success': result.success,
        'n_events': len(event_data_list),
        'sm_min_used': float(sm_min),
        'sm_max_used': float(sm_max)
    }


print("Aggregated calibration function defined.")



def prepare_class_data(class_id, smap_df, classification_df, temp_resampled, 
                       precip_resampled, class_dates, class_event_info=None, 
                       use_aggregated=False):
    """
    Prepare data for a specific rainfall class.
    
    Parameters:
    -----------
    use_aggregated : bool
        If True, aggregate data over 5-day windows per event
        If False, use daily data
    
    Returns:
    --------
    list of dicts : Each dict contains data for one grid point in this class.
        Each dict includes 'sm_global_min' and 'sm_global_max' computed over
        the FULL SMAP time series for that location (not just the calibration
        subset), so that S_relative = (S_raw - S_min) / (S_max - S_min) is
        anchored to the true residual moisture and saturation extremes.
    """
    print(f"\nPreparing data for Class {class_id}...")
    print(f"  Mode: {'AGGREGATED (5-day windows)' if use_aggregated else 'DAILY'}")
    
    # Get grid points belonging to this class
    class_points = classification_df[classification_df['rainfall_class'] == class_id]
    print(f"  Grid points in class: {len(class_points)}")
    
    # Get dates for this class
    dates = class_dates[class_id]
    print(f"  Dates for calibration: {len(dates)}")
    
    if use_aggregated and class_event_info is not None:
        event_df = class_event_info[class_id]
        print(f"  Number of rainfall events: {event_df['event_date'].nunique()}")
    
    # DEBUG: Check coordinate and date ranges
    print(f"\n  DEBUG INFO:")
    print(f"    Class point lat range: {class_points['latitude'].min():.4f} to {class_points['latitude'].max():.4f}")
    print(f"    Class point lon range: {class_points['longitude'].min():.4f} to {class_points['longitude'].max():.4f}")
    print(f"    SMAP lat range: {smap_df['latitude'].min():.4f} to {smap_df['latitude'].max():.4f}")
    print(f"    SMAP lon range: {smap_df['longitude'].min():.4f} to {smap_df['longitude'].max():.4f}")
    print(f"    Resampled temp has {len(temp_resampled)} records, {temp_resampled['smap_lat'].nunique()} unique SMAP points")
    print(f"    Resampled precip has {len(precip_resampled)} records, {precip_resampled['smap_lat'].nunique()} unique SMAP points")
    
    # Prepare data for each grid point
    grid_data_list = []
    no_smap = 0
    no_temp = 0
    no_precip = 0
    insufficient_data = 0
    
    # Use tolerance for coordinate matching (floating point precision)
    coord_tolerance = 0.001  # degrees
    
    for idx, row in class_points.iterrows():
        lat = row['latitude']
        lon = row['longitude']
        
        # ------------------------------------------------------------------
        # Compute S_min / S_max from the FULL available SMAP time series for
        # this grid point (all dates, not just the calibration subset).
        # These represent the true residual moisture (S_min, wilting point)
        # and saturation (S_max, max porosity) for this location.
        # ------------------------------------------------------------------
        smap_full = smap_df[
            (np.abs(smap_df['latitude'] - lat) < coord_tolerance) &
            (np.abs(smap_df['longitude'] - lon) < coord_tolerance)
        ]['soil_moisture']

        if len(smap_full) == 0:
            no_smap += 1
            continue

        sm_global_min = float(smap_full.min())
        sm_global_max = float(smap_full.max())

        # Get SMAP data filtered to the calibration dates
        smap_subset = smap_df[
            (np.abs(smap_df['latitude'] - lat) < coord_tolerance) & 
            (np.abs(smap_df['longitude'] - lon) < coord_tolerance) &
            (smap_df['date'].isin(dates))
        ].copy()
        
        if len(smap_subset) == 0:
            no_smap += 1
            continue
        
        # Get temperature data for this point and dates (with tolerance)
        temp_subset = temp_resampled[
            (np.abs(temp_resampled['smap_lat'] - lat) < coord_tolerance) & 
            (np.abs(temp_resampled['smap_lon'] - lon) < coord_tolerance) &
            (temp_resampled['date'].isin(dates))
        ].copy()
        
        if len(temp_subset) == 0:
            no_temp += 1
            continue
        
        # Get precipitation data for this point and dates (with tolerance)
        precip_subset = precip_resampled[
            (np.abs(precip_resampled['smap_lat'] - lat) < coord_tolerance) & 
            (np.abs(precip_resampled['smap_lon'] - lon) < coord_tolerance) &
            (precip_resampled['date'].isin(dates))
        ].copy()
        
        if len(precip_subset) == 0:
            no_precip += 1
            continue
        
        # Merge datasets on date
        smap_subset   = smap_subset.sort_values('time').set_index('time')
        temp_subset   = temp_subset.sort_values('time').set_index('time')
        precip_subset = precip_subset.sort_values('time').set_index('time')
        
        # Create aligned time series
        sm_series   = smap_subset['soil_moisture']
        temp_series = temp_subset.reindex(sm_series.index)['value']
        rain_series = precip_subset.reindex(sm_series.index)['value']
        
        # Drop NaN values
        valid_idx = sm_series.notna() & temp_series.notna() & rain_series.notna()
        
        if valid_idx.sum() < 20:  # Need at least 20 data points
            insufficient_data += 1
            continue
        
        sm_series   = sm_series[valid_idx]
        temp_series = temp_series[valid_idx]
        rain_series = rain_series[valid_idx]
        
        grid_data_list.append({
            'lat': lat,
            'lon': lon,
            'sm_series': sm_series,
            'temp_series': temp_series,
            'rain_series': rain_series,
            'n_points': len(sm_series),
            # Full-series normalisation anchors
            'sm_global_min': sm_global_min,
            'sm_global_max': sm_global_max
        })
    
    print(f"  Valid grid points with sufficient data: {len(grid_data_list)}")
    print(f"  DEBUG - Points lost:")
    print(f"    No SMAP data: {no_smap}")
    print(f"    No temperature data: {no_temp}")
    print(f"    No precipitation data: {no_precip}")
    print(f"    Insufficient data points: {insufficient_data}")
    
    # If aggregated mode, convert daily time series to event-based aggregated data
    if use_aggregated and class_event_info is not None:
        print(f"\n  Creating aggregated event data...")
        event_df = class_event_info[class_id]
        
        # Group by event_date to find events
        events = event_df.groupby('event_date')
        print(f"  Total rainfall events: {len(events)}")
        
        MIN_EVENTS = 2  # minimum events required per grid point
        aggregated_grid_data = []
        
        for grid_point in grid_data_list:
            event_data_list = []
            
            # Create a DataFrame from time series for easier event grouping
            grid_df = pd.DataFrame({
                'time': grid_point['sm_series'].index,
                'date': pd.to_datetime(grid_point['sm_series'].index).date,
                'sm': grid_point['sm_series'].values,
                'temp': grid_point['temp_series'].values,
                'rain': grid_point['rain_series'].values
            })
            
            # Merge with event info
            grid_df = grid_df.merge(
                event_df[['date', 'event_date']],
                on='date',
                how='left'
            )
            
            # Group by event
            for event_date, event_group in grid_df.groupby('event_date'):
                if pd.isna(event_date):
                    continue
                
                event_group = event_group.sort_values('time')
                
                if len(event_group) < 2:  # Need at least start and end
                    continue
                
                # Extract event aggregated values (raw SM values, not normalised yet)
                sm_start   = event_group['sm'].iloc[0]
                sm_end     = event_group['sm'].iloc[-1]
                rain_total = event_group['rain'].sum()
                temp_mean  = event_group['temp'].mean()
                window_days = len(event_group)

                # Day-of-year of the mid-point date of this calibration window
                mid_time = event_group['time'].iloc[len(event_group) // 2]
                doy_mid  = int(pd.to_datetime(mid_time).day_of_year)

                event_data_list.append({
                    'sm_start':   sm_start,
                    'sm_end':     sm_end,
                    'rain_total': rain_total,
                    'temp_mean':  temp_mean,
                    'window_days': window_days,
                    'doy_mid':    doy_mid   # mid-window Julian day for dynamic Ra
                })
            
            if len(event_data_list) >= MIN_EVENTS:
                aggregated_grid_data.append({
                    'lat': grid_point['lat'],
                    'lon': grid_point['lon'],
                    'event_data_list': event_data_list,
                    'n_events': len(event_data_list),
                    # Pass full-series normalisation anchors through
                    'sm_global_min': grid_point['sm_global_min'],
                    'sm_global_max': grid_point['sm_global_max']
                })
        
        print(f"  Valid grid points with >= {MIN_EVENTS} events each: {len(aggregated_grid_data)} / {len(grid_data_list)}")
        return aggregated_grid_data
    
    return grid_data_list

print("Data preparation function defined.")



def calibrate_sm2rain_pooled(grid_data_list, T_filter):
    """
    POOLED calibration: merge all events from all stations in a class into a
    single dataset, then run ONE optimisation.

    The optimizer sees  N_stations × N_events  relations simultaneously
    (e.g. 25 stations × 25 windows = 625 relations for one class).

    Each station keeps its own S_min / S_max anchors so that the relative
    soil moisture is physically meaningful across stations.

    Parameters
    ----------
    grid_data_list : list of dicts
        Output of prepare_class_data() with USE_AGGREGATED_WINDOWS=True.
        Each dict has keys: event_data_list, sm_global_min, sm_global_max.
    T_filter : float
        Exponential filter time constant (unused in aggregated mode but kept
        for API consistency).

    Returns
    -------
    dict : Calibrated parameters, RMSE, KGE, loss, and dataset size.
    """
    # ------------------------------------------------------------------
    # Build the combined dataset
    # Each row is one (station, event) pair.
    # SM values are normalised per-station using that station's global range.
    # ------------------------------------------------------------------
    all_sm_change_rel = []
    all_sm_mean_rel   = []
    all_rain_totals   = []
    all_temp_means    = []
    all_window_days   = []
    all_Ra_dynamic    = []  # per-event dynamic Ra (mm/day)

    n_total_relations = 0

    for gd in grid_data_list:
        sm_min = gd['sm_global_min']
        sm_max = gd['sm_global_max']
        sm_range = (sm_max - sm_min) if (sm_max - sm_min) > 1e-6 else 1.0
        station_lat = gd['lat']

        for evt in gd['event_data_list']:
            s_start = np.clip((evt['sm_start'] - sm_min) / sm_range, 0.0, 1.0)
            s_end   = np.clip((evt['sm_end']   - sm_min) / sm_range, 0.0, 1.0)

            doy = evt.get('doy_mid', 180)
            Ra  = calculate_ra_mm_day(station_lat, doy)

            all_sm_change_rel.append(s_end - s_start)
            all_sm_mean_rel.append((s_start + s_end) / 2.0)
            all_rain_totals.append(evt['rain_total'])
            all_temp_means.append(evt['temp_mean'])
            all_window_days.append(evt['window_days'])
            all_Ra_dynamic.append(Ra)
            n_total_relations += 1

    sm_change_rel = np.array(all_sm_change_rel)
    sm_mean_rel   = np.array(all_sm_mean_rel)
    rain_totals   = np.array(all_rain_totals)
    temp_means    = np.array(all_temp_means)
    window_days   = np.array(all_window_days)
    Ra_dynamic    = np.array(all_Ra_dynamic)

    print(f"  Pooled dataset: {len(grid_data_list)} stations × events → "
          f"{n_total_relations} total relations")

    # ------------------------------------------------------------------
    # Objective function operating on the full pooled dataset
    # Note: Zstar here is dimensionless storage capacity (mm per unit SM).
    # The SM changes are already in relative [0,1] units; we include
    # sm_range per-station above, but for pooled mode we use a single
    # representative Zstar that acts on the normalised change directly.
    # ------------------------------------------------------------------
    def objective(params):
        Zstar, Ks, lam, Kc = params
        try:
            PET_daily    = np.maximum(0.0, 0.0023 * (temp_means + 17.8) * Ra_dynamic)
            storage_term = Zstar * sm_change_rel          # Zstar scales normalised ΔS
            drain_term   = Ks * window_days * np.power(np.maximum(sm_mean_rel, 0.0), lam)
            et_term      = Kc * PET_daily * window_days
            estimated    = np.maximum(0.0, storage_term + drain_term + et_term)
            return compute_objective(estimated, rain_totals, OBJECTIVE_FUNCTION)
        except Exception:
            return 1e6

    bounds = [
        (1.0,  150.0),   # Zstar (mm per unit relative SM)
        (1.0,  200.0),   # Ks (mm/day)
        (2.0,   20.0),   # lambda
        (0.0,    1.5),   # Kc
    ]

    result = differential_evolution(
        objective, bounds,
        seed=83, maxiter=1000, popsize=25,
        tol=0.005, atol=0.005, workers=1
    )

    Zstar_opt, Ks_opt, lam_opt, Kc_opt = result.x

    # Final metrics
    PET_daily  = np.maximum(0.0, 0.0023 * (temp_means + 17.8) * Ra_dynamic)
    estimated  = np.maximum(0.0,
        Zstar_opt * sm_change_rel
        + Ks_opt * window_days * np.power(np.maximum(sm_mean_rel, 0.0), lam_opt)
        + Kc_opt * PET_daily * window_days
    )
    rmse_final    = float(np.sqrt(np.mean((estimated - rain_totals) ** 2)))
    kge_final     = float(calculate_kge(estimated, rain_totals))
    pearson_final = calculate_pearson_r(estimated, rain_totals)

    return {
        'Zstar': Zstar_opt,
        'Ks':    Ks_opt,
        'lam':   lam_opt,
        'Kc':    Kc_opt,
        'rmse':  rmse_final,
        'kge':   kge_final,
        'pearson_r': pearson_final,
        'loss':  result.fun,
        'objective_fn':    OBJECTIVE_FUNCTION,
        'success':         result.success,
        'n_stations':      len(grid_data_list),
        'n_relations':     n_total_relations,
    }


# ======================================================================
# Main calibration loop
# ======================================================================
all_class_results = {}

for class_id in range(1, NUM_CLASSES + 1):
    if class_id not in class_dates:
        print(f"\n{'='*80}")
        print(f"Skipping Class {class_id} - no dates available")
        continue

    strategy_label = 'POOLED' if POOLED_CALIBRATION else 'PER-POINT'
    print(f"\n{'='*80}")
    print(f"CLASS {class_id} CALIBRATION  [objective: {OBJECTIVE_FUNCTION}  |  strategy: {strategy_label}]")
    print(f"{'='*80}")

    # Prepare data for this class
    grid_data_list = prepare_class_data(
        class_id, smap_df, classification_df,
        temp_resampled, precip_resampled, class_dates,
        class_event_info, USE_AGGREGATED_WINDOWS
    )

    if len(grid_data_list) == 0:
        print(f"No valid data for Class {class_id}")
        continue

    # ------------------------------------------------------------------
    if POOLED_CALIBRATION and USE_AGGREGATED_WINDOWS:
        # ── POOLED: one optimisation across all stations × events ───────
        print(f"\nRunning POOLED calibration over {len(grid_data_list)} stations...")
        pooled_result = calibrate_sm2rain_pooled(grid_data_list, T_EXPONENTIAL_FILTER)

        class_summary = {
            'class_id':       class_id,
            'objective_fn':   OBJECTIVE_FUNCTION,
            'strategy':       'pooled',
            'n_grid_points':  len(grid_data_list),
            'n_relations':    pooled_result['n_relations'],
            'best_loss':      pooled_result['loss'],
            'best_rmse':      pooled_result['rmse'],
            'best_kge':       pooled_result['kge'],
            'best_pearson_r': pooled_result.get('pearson_r', float('nan')),
            'mean_rmse':      pooled_result['rmse'],   # single result
            'std_rmse':       0.0,
            'mean_kge':       pooled_result['kge'],
            'mean_pearson_r': pooled_result.get('pearson_r', float('nan')),
            'best_parameters': {
                'Zstar': pooled_result['Zstar'],
                'Ks':    pooled_result['Ks'],
                'lam':   pooled_result['lam'],
                'Kc':    pooled_result['Kc'],
            },
            'all_results': [pooled_result]
        }

        print(f"\n{'='*80}")
        print(f"CLASS {class_id} POOLED CALIBRATION SUMMARY  [objective: {OBJECTIVE_FUNCTION}]")
        print(f"{'='*80}")
        print(f"Stations in class : {pooled_result['n_stations']}")
        print(f"Total relations   : {pooled_result['n_relations']}")
        print(f"RMSE              : {pooled_result['rmse']:.4f} mm")
        print(f"KGE               : {pooled_result['kge']:.4f}")
        print(f"Pearson r         : {pooled_result.get('pearson_r', float('nan')):.4f}")
        print(f"\nCalibrated Parameters:")
        print(f"  Z* = {pooled_result['Zstar']:.2f} mm")
        print(f"  Ks = {pooled_result['Ks']:.4f} mm/day")
        print(f"  lambda = {pooled_result['lam']:.4f}")
        print(f"  Kc = {pooled_result['Kc']:.4f}")
        print(f"{'='*80}")

    else:
        # ── PER-POINT: calibrate each station independently ─────────────
        class_results = []
        print(f"\nCalibrating {len(grid_data_list)} grid points independently...")

        for grid_data in tqdm(grid_data_list, desc=f"Class {class_id}"):
            try:
                if USE_AGGREGATED_WINDOWS:
                    result = calibrate_sm2rain_aggregated(
                        grid_data['event_data_list'],
                        grid_data['lat'],
                        T_EXPONENTIAL_FILTER,
                        sm_global_min=grid_data.get('sm_global_min'),
                        sm_global_max=grid_data.get('sm_global_max')
                    )
                    result['lat'] = grid_data['lat']
                    result['lon'] = grid_data['lon']
                    result['n_points'] = grid_data['n_events']
                else:
                    result = calibrate_sm2rain_parameters(
                        grid_data['sm_series'],
                        grid_data['temp_series'],
                        grid_data['rain_series'],
                        grid_data['lat'],
                        T_EXPONENTIAL_FILTER,
                        sm_global_min=grid_data.get('sm_global_min'),
                        sm_global_max=grid_data.get('sm_global_max')
                    )
                    result['lat'] = grid_data['lat']
                    result['lon'] = grid_data['lon']
                    result['n_points'] = grid_data['n_points']

                class_results.append(result)

            except Exception as e:
                print(f"\nError calibrating ({grid_data['lat']:.4f}, {grid_data['lon']:.4f}): {e}")

        if len(class_results) == 0:
            print(f"No successful calibrations for Class {class_id}")
            continue

        best_idx    = np.argmin([r['loss']  for r in class_results])
        best_params = class_results[best_idx]
        rmse_values = [r['rmse'] for r in class_results]
        kge_values  = [r['kge']  for r in class_results]

        class_summary = {
            'class_id':       class_id,
            'objective_fn':   OBJECTIVE_FUNCTION,
            'strategy':       'per_point',
            'n_grid_points':  len(grid_data_list),
            'n_successful':   len(class_results),
            'best_loss':      best_params['loss'],
            'best_rmse':      best_params['rmse'],
            'best_kge':       best_params['kge'],
            'best_pearson_r': best_params.get('pearson_r', float('nan')),
            'mean_rmse':      np.mean(rmse_values),
            'std_rmse':       np.std(rmse_values),
            'mean_kge':       np.mean([v for v in kge_values if v != -9999.0]),
            'mean_pearson_r': float(np.mean([r['pearson_r'] for r in class_results if not np.isnan(r.get('pearson_r', float('nan')))])),
            'best_parameters': {
                'Zstar': best_params['Zstar'],
                'Ks':    best_params['Ks'],
                'lam':   best_params['lam'],
                'Kc':    best_params['Kc'],
            },
            'best_location': {'lat': best_params['lat'], 'lon': best_params['lon']},
            'all_results': class_results
        }

        print(f"\n{'='*80}")
        print(f"CLASS {class_id} PER-POINT CALIBRATION SUMM ARY  [objective: {OBJECTIVE_FUNCTION}]")
        print(f"{'='*80}")
        print(f"Grid points calibrated : {len(class_results)} / {len(grid_data_list)}")
        pearson_values = [r.get('pearson_r', float('nan')) for r in class_results]
        valid_pearson  = [v for v in pearson_values if not np.isnan(v)]
        print(f"Best  RMSE     : {best_params['rmse']:.4f} mm")
        print(f"Best  KGE      : {best_params['kge']:.4f}")
        print(f"Best  Pearson r: {best_params.get('pearson_r', float('nan')):.4f}")
        print(f"Mean  RMSE     : {np.mean(rmse_values):.4f} ± {np.std(rmse_values):.4f} mm")
        print(f"Mean  KGE      : {np.mean([v for v in kge_values if v != -9999.0]):.4f}")
        print(f"Mean  Pearson r: {np.mean(valid_pearson):.4f}" if valid_pearson else "Mean  Pearson r: nan")
        print(f"\nBest Parameters (station with best {OBJECTIVE_FUNCTION}):")
        print(f"  Z* = {best_params['Zstar']:.2f} mm")
        print(f"  Ks = {best_params['Ks']:.4f} mm/day")
        print(f"  lambda = {best_params['lam']:.4f}")
        print(f"  Kc = {best_params['Kc']:.4f}")
        print(f"  Location: ({best_params['lat']:.4f}, {best_params['lon']:.4f})")
        print(f"  SM global range: "
              f"[{best_params.get('sm_min_used', float('nan')):.4f}, "
              f"{best_params.get('sm_max_used', float('nan')):.4f}] m³/m³")
        print(f"{'='*80}")

    all_class_results[class_id] = class_summary

    # Save class results to JSON
    output_file = OUTPUT_DIR / f'class_{class_id}_calibration_results.json'
    with open(output_file, 'w') as f:
        json.dump(class_summary, f, indent=2)
    print(f"\nResults saved to: {output_file}")

print(f"\n{'='*80}")
print("ALL CLASSES CALIBRATION COMPLETE")
print(f"{'='*80}")



# Create summary table
summary_data = []

for class_id, results in sorted(all_class_results.items()):
    summary_data.append({
        'Class': class_id,
        # 'N_Points': results['n_successful'],
        'Objective': results.get('objective_fn', 'RMSE'),
        'Best_RMSE': results['best_rmse'],
        'Mean_RMSE': results['mean_rmse'],
        'Best_KGE': results.get('best_kge', float('nan')),
        'Mean_KGE': results.get('mean_kge', float('nan')),
        'Best_PearsonR': results.get('best_pearson_r', float('nan')),
        'Mean_PearsonR': results.get('mean_pearson_r', float('nan')),
        'Zstar': results['best_parameters']['Zstar'],
        'Ks': results['best_parameters']['Ks'],
        'lambda': results['best_parameters']['lam'],
        'Kc': results['best_parameters']['Kc']
    })

summary_df = pd.DataFrame(summary_data)

print("\n" + "="*120)
print(f"SUMMARY: BEST PARAMETERS FOR EACH CLASS  [objective: {OBJECTIVE_FUNCTION}]")
print("="*120)
print(summary_df.to_string(index=False))
print("="*120)

# Save summary to CSV
summary_file = OUTPUT_DIR / 'all_classes_best_parameters.csv'
summary_df.to_csv(summary_file, index=False)
print(f"\nSummary saved to: {summary_file}")

# Save all results to single JSON
all_results_file = OUTPUT_DIR / 'all_classes_calibration_results.json'
with open(all_results_file, 'w') as f:
    json.dump(all_class_results, f, indent=2)
print(f"All results saved to: {all_results_file}")


